#!/bin/bash
set -e

# ==========================================
# CONFIGURATION
# ==========================================
PROJECT_ID=$(gcloud config get-value project)
REGION="asia-south1"
DB_INSTANCE_CONNECTION_NAME="${PROJECT_ID}:${REGION}:cortex-prod-db"
GCS_BUCKET="cortex-prod-bucket"

# Secret names in Secret Manager
SECRET_KAFKA_URL="aiven-kafka-bootstrap-servers"
SECRET_DB_PASS="cortex-prod-db-password"
SECRET_GROQ_KEY="cortex-groq-api-key"
SECRET_GEMINI_KEY="cortex-gemini-api-key"
SECRET_KAFKA_CA="aiven-kafka-ca-cert"
SECRET_KAFKA_CERT="aiven-kafka-service-cert"
SECRET_KAFKA_KEY="aiven-kafka-service-key"

# Helper to fetch secret
fetch_secret() {
    gcloud secrets versions access latest --secret="$1"
}

# ==========================================
# 1. FETCH CERTS & SETUP SSL
# ==========================================
echo "🔐 Fetching certificates..."
mkdir -p certs

fetch_secret "$SECRET_KAFKA_CA" > certs/ca.pem
fetch_secret "$SECRET_KAFKA_CERT" > certs/service.cert
fetch_secret "$SECRET_KAFKA_KEY" > certs/service.key

echo "🛠️ Converting certificates to Java KeyStore..."

# Create TrustStore
rm -f certs/truststore.jks
keytool -import -noprompt -alias ca -file certs/ca.pem -keystore certs/truststore.jks -storepass changeit

# Create KeyStore (PEM -> PKCS12 -> JKS)
rm -f certs/keystore.p12 certs/keystore.jks
openssl pkcs12 -export -in certs/service.cert -inkey certs/service.key \
    -out certs/keystore.p12 -name service -CAfile certs/ca.pem -caname root -passout pass:changeit
keytool -importkeystore -deststorepass changeit -destkeypass changeit -destkeystore certs/keystore.jks \
    -srckeystore certs/keystore.p12 -srcstoretype PKCS12 -srcstorepass changeit -alias service

# Cleanup raw keys
rm certs/service.key certs/service.cert certs/keystore.p12

# ==========================================
# 2. GENERATE .env FILE
# ==========================================
echo "📝 Generating .env file..."

cat > .env <<EOF
# Auto-generated by deploy.sh — $(date)
# GCP
GCP_PROJECT_ID=${PROJECT_ID}
GCP_LOCATION=${REGION}
GCS_BUCKET_NAME=${GCS_BUCKET}
DB_INSTANCE_CONNECTION_NAME=${DB_INSTANCE_CONNECTION_NAME}

# Database
DB_PASSWORD=$(fetch_secret "$SECRET_DB_PASS")

# Kafka
KAFKA_BOOTSTRAP_SERVERS=$(fetch_secret "$SECRET_KAFKA_URL")

# AI Keys
GROQ_API_KEY=$(fetch_secret "$SECRET_GROQ_KEY")
GEMINI_API_KEY=$(fetch_secret "$SECRET_GEMINI_KEY")

# Kafka SSL (paths inside Docker containers)
KAFKA_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/truststore.jks
KAFKA_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/keystore.jks
KAFKA_SSL_KEY_PASSWORD=changeit
KAFKA_SSL_KEYSTORE_PASSWORD=changeit
KAFKA_SSL_TRUSTSTORE_PASSWORD=changeit
EOF

chmod 600 .env
echo "✅ .env file created (owner-read-only)"

# ==========================================
# 3. DEPLOY
# ==========================================
echo "🚀 Starting Docker containers..."
docker compose -f docker-compose.prod.yaml up -d --build --remove-orphans

echo "✅ Deployment complete!"
