spring.application.name=cortex-rag-orchestration

# Kafka Topics
app.kafka.topic.media=cortex.file.ingested.media

# Kafka Common
spring.kafka.consumer.group-id=cortex-rag-orchestration-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Database Common
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# AI Models (Defaults)
spring.ai.openai.audio.transcription.options.model=whisper-large-v3
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.task-type=RETRIEVAL_DOCUMENT
spring.ai.google.genai.embedding.text.options.dimensions=768
