# Production Configuration
server.port=8083

# GCP Config
spring.cloud.gcp.project-id=${GCP_PROJECT_ID}
spring.cloud.gcp.storage.enabled=true
spring.cloud.gcp.location=${GCP_LOCATION}
gcs.bucket=${GCS_BUCKET_NAME}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.security.protocol=${SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL}
spring.kafka.properties.ssl.truststore.location=${SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION}
spring.kafka.properties.ssl.truststore.password=${SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_PASSWORD}
spring.kafka.properties.ssl.keystore.location=${SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_LOCATION}
spring.kafka.properties.ssl.keystore.password=${SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_PASSWORD}
spring.kafka.properties.ssl.key.password=${SPRING_KAFKA_PROPERTIES_SSL_KEY_PASSWORD}

# AI Keys
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=${GROQ_BASE_URL}
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
# Vertex AI Config
spring.ai.vertex.ai.gemini.project-id=${GCP_PROJECT_ID}
spring.ai.vertex.ai.gemini.location=${GCP_LOCATION}
