spring:
  application:
    name: cortex-gateway
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  session:
    store-type: redis
    timeout: 24h
    redis:
      namespace: cortex:sessions # Match dev config
  
server:
  forward-headers-strategy: native
  port: 8080

app:
  jwt:
    secret: ${INTERNAL_JWT_SECRET}
    expiration-seconds: 3600000 # 1 hour
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
