spring:
  application:
    name: cortex-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: files
              uri: http://${INGESTION_HOST:localhost}:8081
              predicates:
                - Path=/api/v1/files/**

            - id: webhook
              uri: http://${INGESTION_HOST:localhost}:8081
              predicates:
                - Path=/api/v1/webhook/**

            - id: search
              uri: http://${RAG_HOST:localhost}:8083
              predicates:
                - Path=/api/v1/search/**

  grpc:
    client:
      channels:
        ingestion-channel:
          address: static://${INGESTION_HOST:localhost}:9090
          negotiation-type: plaintext

server:
  port: 8080
