spring.application.name=cortex-ingestion

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB

# Kafka Topics
app.kafka.topic.file-ingested.media=cortex.file.ingested.media
app.kafka.topic.file-ingested.document=cortex.file.ingested.document
app.kafka.topic.pipeline-events=cortex.pipeline.events

# Kafka Common
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=cortex-ingestion-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Database Common
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
