package com.cortex.cortex_common.model;

public enum PipelineEventEnum {
  PIPELINE_STARTED,
  CHUNKING_STARTED,
  CHUNKING_COMPLETE,
  CHUNK_UPLOAD_STARTED,
  CHUNK_UPLOAD_COMPLETE,
  MEDIA_CHUNK_READY,
  VISION_ANALYSIS_STARTED,
  VISION_ANALYSIS_COMPLETE,
  TRANSCRIPTION_STARTED,
  TRANSCRIPTION_COMPLETE,
  EMBEDDING_COMPLETE,
  PIPELINE_COMPLETE,
  UPLOAD_REJECTED
}

// TODO: Add an error event and have the details in the message. TBD